"""Add user presence status

Revision ID: 169a5488c957
Revises: c4989b802e31
Create Date: 2026-10-03 23:59:00.500527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169a5488c957'
down_revision: Union[str, Sequence[str], None] = 'c4989b802e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('presence_mode', sa.String(length=20), server_default='online', nullable=False))
    op.add_column('users', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen_at')
    op.drop_column('users', 'presence_mode')
    # ### end Alembic commands ###
