"""Add profile connection card fields

Revision ID: b9bcfb5a8cf1
Revises: e33882fd25ea
Create Date: 2026-09-29 13:19:00.950146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bcfb5a8cf1'
down_revision: Union[str, Sequence[str], None] = 'e33882fd25ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('class_year', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('aspiration', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('looking_for', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('ask_me_about', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('current_obsession', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'current_obsession')
    op.drop_column('profiles', 'ask_me_about')
    op.drop_column('profiles', 'looking_for')
    op.drop_column('profiles', 'aspiration')
    op.drop_column('profiles', 'class_year')
    # ### end Alembic commands ###
