"""Add post it colors

Revision ID: c4989b802e31
Revises: b9bcfb5a8cf1
Create Date: 2026-09-29 18:57:19.571458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4989b802e31'
down_revision: Union[str, Sequence[str], None] = 'b9bcfb5a8cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_its', sa.Column('color', sa.String(length=30), server_default='yellow', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_its', 'color')
    # ### end Alembic commands ###
