"""Add verification welcome status

Revision ID: e33882fd25ea
Revises: 3531c0080cc5
Create Date: 2026-09-28 23:18:25.542770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33882fd25ea'
down_revision: Union[str, Sequence[str], None] = '3531c0080cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_welcome_seen', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_welcome_seen')
    # ### end Alembic commands ###
